name: Rust Test

on: [push]

jobs:
  TestAndDeploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Branch ğŸ“¥
      uses: actions/checkout@v2

    - name: Run Tests ğŸ§ª
      run: cargo test --verbose

    - name: Use Node.js ğŸ“¦
      uses: actions/setup-node@v1
      with:
        node-version: '13.x'

    - name: Install GUI Build Dependencies ğŸ“¦
      run: |
        sudo apt-get update
        sudo apt-get install -y curl rsync
        curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh 

    - name: Build GUI ğŸ› ï¸
      run: |
        wasm-pack build --release
        cd gui
        npm install
        npm run build
        
    - name: Install SSH Client ğŸ›°ï¸
      uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}
      
    - name: Deploy ğŸš€
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        SSH: true
        BRANCH: gh-pages
        FOLDER: gui/build
